# qr_preset_studio/infrastructure/rendering/constants.py
FINDER_SIZE = 7
FINDER_BALL_OFFSET = 2
FINDER_BALL_SIZE = 3
QR_BORDER_MODULES = 4
PREVIEW_MAX_SIZE = (900, 900)

PRINT_BASE_DPI = 300
MAX_QR_LAYER_SIDE = 6144
MAX_EXPORT_SIDE = 12000
ROUNDED_QR_LAYER_SUPERSAMPLE = 2.0
